return {
	"If this compiles , it's a miracle...",
	"Typing at 140wpm brat...",
	"Forging code with surgical precision...",
	"Leaving trial of perfectly written functions...",
	"Ah yes, another bug——totally expected!",
	"Stop stalking me!!",
	"Coding like a maniac!",
	"Crafting code with elegance",
	"Each keystorke unlocks new possibility!!",
	"Perfetction takes time——luckily,I'm fast.",
	"Watch and learn , ameatures",
	"Syntax bows before my presence",
	"Coding at a level you wouldn't understand",
	"Oh, you use VS Code , That's cute.",
	'Fixing bugs faster than you can type "Hello world"',
	"Neovim isn't hard——you're just soft.",
	"This is Neovim. Not VS Code with 50 extensions holding your hand.",
	"If you need a mouse, you're already behind.",
	"You still use a GUI? How adorable.",
}
